apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-portal
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port: 
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "my.hmtest.de"
    - "domain.api.hmtest.de"
    - "pki.api.hmtest.de"
    - "eab.api.hmtest.de"
  - port: 
      number: 80
      name: http-acme
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - acme.hmtest.de
  - port:
      number: 443
      name: https-acme
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - acme.hmtest.de
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: portal-cert
    hosts:
    - "my.hmtest.de"
    - "domain.api.hmtest.de"
    - "pki.api.hmtest.de"
    - "eab.api.hmtest.de"