---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: base
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: istiod
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
  values:
    global:
      logAsJson: true
    meshConfig:
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
      defaultConfig:
        tracing:
          sampling: 100
    pilot:
      autoscaleEnabled: false
      replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingressgateway
  namespace: istio-ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    force: true
    remediation:
      retries: 5
    crds: CreateReplace
