---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: base
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: istiod
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      logAsJson: true
    meshConfig:
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
    pilot:
      autoscaleEnabled: false
      replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway
  namespace: istio-ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    force: true
    remediation:
      retries: 5

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway-internal
  namespace: istio-ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    force: true
    remediation:
      retries: 5