---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    defaultSettings:
      replicaAutoBalance: "best-effort"
      orphanAutoDeletion: "true"
    persistence:
      defaultClassReplicaCount: 2
