apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspaces-cert
  namespace: istio-ingress
spec:
  commonName: workspaces.it.hm.edu
  dnsNames:
    - "workspaces.it.hm.edu"
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod
  secretName: workspaces-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspaces-wild-cert
  namespace: istio-ingress
spec:
  commonName: "*.workspaces.it.hm.edu"
  dnsNames:
    - "*.workspaces.it.hm.edu"
  issuerRef:
    kind: Issuer
    name: acme-issuer-dns
  secretName: workspaces-wild-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pw-pusher-cert
  namespace: istio-ingress
spec:
  commonName: pwpusher.it.hm.edu
  dnsNames:
    - "pwpusher.it.hm.edu"
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod
  secretName: pw-pusher-cert
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbox-cert
  namespace: istio-ingress
spec:
  commonName: netbox.it.hm.edu
  dnsNames:
    - "netbox.it.hm.edu"
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod
  secretName: netbox-cert
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sso-test-cert
  namespace: istio-ingress
spec:
  commonName: sso-test.it.hm.edu
  dnsNames:
    - "sso-test.it.hm.edu"
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod
  secretName: sso-test-cert
