apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspaces-cert
  namespace: istio-ingress
spec:
  commonName: workspaces.it.hm.edu
  dnsNames:
    - workspaces.it.hm.edu
    - *.workspaces.it.hm.edu
  issuerRef:
    kind: ClusterIssuer
    name: acme-issuer-dns
  secretName: workspaces-cert
