apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workspaces-cert
  namespace: istio-ingress
spec:
  commonName: workspaces.it.hm.edu
  dnsNames:
    - "workspaces.it.hm.edu"
    - "*.workspaces.it.hm.edu"
  issuerRef:
    kind: Issuer
    name: acme-issuer-dns
  secretName: workspaces-cert
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pw-pusher-cert
  namespace: istio-ingress
spec:
  commonName: pwpusher.it.hm.edu
  dnsNames:
    - "pwpusher.it.hm.edu"
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod
  secretName: pw-pusher-cert
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kimai-cert
  namespace: istio-ingress
spec:
  commonName: kimai.it.hm.edu
  dnsNames:
    - "kimai.it.hm.edu"
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod
  secretName: kimai-cert
