apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-issuer-dns
  namespace: istio-ingress
spec:
  acme:
    email: noreply@hm.edu
    externalAccountBinding:
      keyID: WZsr6KK6Bows4SGuXvkYCVvUc2v362rj
      keySecretRef:
        key: secret
        name: eab-secret-dns
    privateKeySecretRef:
      name: acme-prod-cluster-dns
    server: https://acme.hm.edu/acme/acme/directory
    solvers:
    - dns01:
        acmeDNS:
          host: https://certauth.it.hm.edu
          accountSecretRef:
            name: acme-dns
            key: acmedns.json