apiVersion: v1
kind: Secret
metadata:
    name: acme-dns
    namespace: istio-ingress
stringData:
    acmedns.json: ENC[AES256_GCM,data:OGtdGvojN9G95STHQM+HQLKmfFsBnqaTSBNLQN4q4N6kQpk8Nl6wdBXHGXJd0Y9ipqiOGJqkONTnqlJqRroawD7Jk7nNpkhOg++GNYFh7OZo3F4N9Jgj1O8H+I0kEFg0P1sg7hUeDHJ68IAhrjOHhwMjieZT0uabXUM/YzwyIYgYmn306VQGfmXjGN3jl26cBwCVUhtHyEotNuyFoctFYgR1Ccy16YGPknrqO5kwftjHHLeLZQ6plqi7HSWr5z/lf89v4Eu7R5QPtCJ7pY0aPvD05uiweE9DbiXKKoSqiGJPBw7YLxCIfZFI7/38AtJ9L+BxGjsAkrW/YxMQB1E+g1GiUBi4gHcxXHvRmDOsltoDtXQpibb/gPHVSF5QDg4qEex3jgg7Sk2maJfPSC1UR5Ig,iv:AigO2mVH1siYCahEDR+wC1Jhw3hl47EXQnMLnwiOjRI=,tag:bOA4XpNbe3YFD4jMBxdHPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSWJ3cnlUVEx4TVI2SUtx
            K29RVmVrdFB0VGJRUndESERNaElHL0dWSGhRCnd1YURLYmRlOUthQTlyYlI3RzZX
            bDUyQTllaGxsM0hvMGJHTC81UzRObHMKLS0tIEtsNFZwaG5lb2RHaHkvMGt1NjU0
            OXY2eU9xTHY5NWdoQ3duT2JyL3Jvc00KgHZ4kIcZtgxHJcJObHD7BENO0YbfNQLt
            ojktT6NViLK+thiHOhaNwC7OMJ+ojWJJSyhWr3nGigCTIoZcr+yctw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T12:00:53Z"
    mac: ENC[AES256_GCM,data:ZKDa+1LxhLdOU6tEuCVQGUbg5A9EpDQgT+V+AfKxfaTfu5qFc0KuRbbZxH8HkJzu1knn1qdMLUopm14y5qxXuoLp2oou68IVPcseTEZ21Fpa9XUcHZupqPghlIX3V7vcIrPRmPHRpfvw9TiLc3GGlowoRycut3rj7fJnYyMLpBI=,iv:k0fkzHRqFW5l8usgh6ppoFpo4iWQd2XiCBy2k+jm2/8=,tag:vmrYFH/76+T1G1fGEuWZ1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: eab-secret-dns
    namespace: istio-ingress
stringData:
    secret: ENC[AES256_GCM,data:445fi+pd6P7+WPwgkCnVYdx8o/l0VXTsCxgPw+RJydkjzyQlPMp6MI1mHA==,iv:NTaElI4jQcHwfMuk+aqFh2m6pPwRipVpEKudxSM2Ym0=,tag:I+8xNM6IQF5vfTtuAPwJFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSWJ3cnlUVEx4TVI2SUtx
            K29RVmVrdFB0VGJRUndESERNaElHL0dWSGhRCnd1YURLYmRlOUthQTlyYlI3RzZX
            bDUyQTllaGxsM0hvMGJHTC81UzRObHMKLS0tIEtsNFZwaG5lb2RHaHkvMGt1NjU0
            OXY2eU9xTHY5NWdoQ3duT2JyL3Jvc00KgHZ4kIcZtgxHJcJObHD7BENO0YbfNQLt
            ojktT6NViLK+thiHOhaNwC7OMJ+ojWJJSyhWr3nGigCTIoZcr+yctw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T12:00:53Z"
    mac: ENC[AES256_GCM,data:ZKDa+1LxhLdOU6tEuCVQGUbg5A9EpDQgT+V+AfKxfaTfu5qFc0KuRbbZxH8HkJzu1knn1qdMLUopm14y5qxXuoLp2oou68IVPcseTEZ21Fpa9XUcHZupqPghlIX3V7vcIrPRmPHRpfvw9TiLc3GGlowoRycut3rj7fJnYyMLpBI=,iv:k0fkzHRqFW5l8usgh6ppoFpo4iWQd2XiCBy2k+jm2/8=,tag:vmrYFH/76+T1G1fGEuWZ1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
