---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rittal-exporter
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rittal-exporter
  template:
    metadata:
      labels:
        app: rittal-exporter
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readonlyRootFilesystem: true
      containers:
        - image: ghcr.io/hm-edu/rittal-exporter:v1.5.33@sha256:85b58c8c82e6f0af965398318a5afd9aae9978dc1e611276f6d24e5c0400e932
          imagePullPolicy: Always
          name: app
          command: ["/usr/local/bin/rittal-exporter"]
          ports:
            - containerPort: 9191
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/rittal-exporter/
              name: rittal-monitoring
      volumes:
        - name: rittal-monitoring
          configMap:
            name: rittal-monitoring
            items:
              - key: config.yaml
                path: config.yaml        
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: rittal-exporter
  labels:
    app: rittal-exporter
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 9191
      targetPort: 9191
  selector:
    app: rittal-exporter