---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
    crds: CreateReplace
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    global:
      clusterDomain: cluster.local
      dnsNamespace: kube-system
      dnsService: rke2-coredns-rke2-coredns
    loki:
      structuredConfig:
        auth_enabled: false
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
        memberlist:
          join_members: ["loki-memberlist"]
        limits_config:
          retention_period: 14d
          retention_stream:
            - selector: '{pod=~"loki-canary-.*"}'
              priority: 2
              period: 24h
            - selector: '{namespace=~"longhorn-system|default|minio|monitoring|istio-system|flux-system|cert-manager|kube-system"}'
              priority: 2
              period: 72h
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
        schema_config:
          configs:
            - from: "2021-08-01"
              store: boltdb-shipper
              object_store: aws
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
            - from: "2022-12-26"
              store: boltdb-shipper
              object_store: aws
              schema: v12
              index:
                prefix: loki_index_
                period: 24h

        storage_config:
          aws:
            s3: null
            endpoint: http://minio.minio.svc.cluster.local:9000
            bucketnames: loki
            insecure: true
            s3forcepathstyle: true
          boltdb_shipper:
            active_index_directory: /var/loki/index
            cache_location: /var/loki/index_cache
            shared_store: s3
        common:
          path_prefix: /var/loki
          replication_factor: 3
          ring:
            kvstore:
              store: memberlist
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          ring:
            kvstore:
              store: memberlist
        distributor:
          ring:
            kvstore:
              store: memberlist
        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
        ingester:
          max_chunk_age: 1h
          lifecycler:
            ring:
              kvstore:
                store: memberlist
        analytics:
          reporting_enabled: false
    gateway:
      enabled: true
      replicas: 3
    write:
      replicas: 3
      persistence:
        storageClass: nfs-client
        size: 10Gi
    read:
      replicas: 3
      extraVolumeMounts:
        - name: loki-rules
          mountPath: /rules/fake
        - name: loki-rules-tmp
          mountPath: /tmp/scratch
        - name: loki-tmp
          mountPath: /tmp/loki-tmp
      extraVolumes:
        - name: loki-rules
          emptyDir: {}
        - name: loki-rules-tmp
          emptyDir: {}
        - name: loki-tmp
          emptyDir: {}
      persistence:
        storageClass: nfs-client
        size: 10Gi
    monitoring:
      dashboards:
        enabled: true
        labels:
          grafana_dashboard: "1"
      serviceMonitor:
        enabled: true
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
  valuesFrom:
    - kind: Secret
      name: loki-values
