---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 10m
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
    crds: CreateReplace
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    loki:
      enabled: true
      config:
        compactor:
          shared_store: s3
          working_directory: /data/loki/boltdb-shipper-compactor
        schema_config:
          configs:
            - from: "2020-10-24"
              index:
                period: 24h
                prefix: index_
              object_store: aws
              schema: v11
              store: boltdb-shipper
        table_manager:
          retention_deletes_enabled: true
          # Customize this: how long should logs be kept?
          retention_period: 2w
        storage_config:
          boltdb_shipper:
            active_index_directory: /data/loki/boltdb-shipper-active
            cache_location: /data/loki/boltdb-shipper-cache
            cache_ttl: 24h
            shared_store: s3
          aws:
            bucketnames: loki
            endpoint: minio.minio:9000
            s3forcepathstyle: true
            insecure: true
      serviceMonitor:
        enabled: false
    promtail:
      enabled: true
      serviceMonitor:
        enabled: false
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
