kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: portal
  name: cert-pv-claim
  labels:
    app: cert
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: portal
  name: cert-config
data:
  ca.json: |
    {
      "address": ":8443",
      "publicAddress": ":443",
      "commonName": "acme.hmtest.de",
      "dnsNames": [
        "acme.hmtest.de"
      ],
      "logger": {
        "format": "json"
      },
      "db": {
        "type": "postgresql",
        "dataSource": "postgresql://acme:acme@postgres.portal.svc.cluster.local/",
        "database": "acme"
      },
      "authority": {
        "type": "sectigocas",
        "provisioners": [
          {
            "type": "ACME",
            "name": "acme",
            "requireEAB": true
          }
        ],
        "template": {},
        "backdate": "1m0s",
        "config":{
          "pkiBackend": "pki-service:8081",
          "eabBackend": "eab-rest-interface:8081"
        }
      },
      "tls": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        ],
        "minVersion": 1.2,
        "maxVersion": 1.3,
        "renegotiation": false
      },
      "storage": "/opt/step",
      "managementHost": "eab-rest-interface:8081"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificates
  namespace: portal
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: certificates
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
      labels:
        app: certificates
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: portal-acme
      containers:
        - image: ghcr.io/hm-edu/certificates:master-68318a6-1666372014 # {"$imagepolicy": "flux-system:certificates"}
          imagePullPolicy: Always
          name: app
          command: ["/usr/local/bin/step-ca"]
          ports:
            - containerPort: 443
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            periodSeconds: 30
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /opt/step
              name: cert
            - mountPath: /home/step/config
              name: cert-config
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://jaeger-collector.istio-system.svc:14268/api/traces
      volumes:
        - name: cert-config
          configMap:
            name: cert-config
            items:
              - key: ca.json
                path: ca.json
        - name: cert
          persistentVolumeClaim:
            claimName: cert-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: portal
  name: certificates
  labels:
    app: certificates
spec:
  type: ClusterIP
  ports:
  - name: acme
    port: 443
    targetPort: 443
  - name: internal
    port: 8443
    targetPort: 8443
  selector:
    app: certificates
