---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner-lrz
  namespace: gitlab-runner-lrz
spec:
  interval: 15m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.53.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    gitlabUrl: https://gitlab.lrz.de
    runners:
      secret: gitlab-runner-secret
      config: |
        [[runners]]
          pre_clone_script = "for i in $(seq 1 5);do getent hosts gitlab.lrz.de && break || sleep 1;done"
          [runners.kubernetes]
            helper_image_flavor = "ubuntu"
            namespace = "gitlab-runner-lrz"
            # Drop ndots for quicker resolution
            [[runners.kubernetes.dns_config.options]]
              name = "ndots"
              value = "1"

    rbac:
      create: true
      rules:
        - resources: [ "pods/attach", "pods/exec"]
          verbs: [ "create", "patch", "delete"]
        - resources: [ "pods", "services" ]
          verbs: [ "get", "watch", "create", "delete"]
        - resources: [ "configmaps", "secrets"]
          verbs: [ "get", "create", "update", "delete"]
        - resources: [ "serviceAccounts"	]
          verbs: [ "get"]