---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner-lrz
  namespace: gitlab-runner-lrz
spec:
  interval: 15m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.70.4
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    gitlabUrl: https://gitlab.lrz.de
    runners:
      secret: gitlab-runner-secret
      config: |
        [[runners]]
          pre_clone_script = "for i in $(seq 1 5);do getent hosts gitlab.lrz.de && break || sleep 1;done"
          [runners.kubernetes]
            helper_image_flavor = "ubuntu"
            namespace = "gitlab-runner-lrz"
            cap_add = ["NET_ADMIN"]
            # Drop ndots for quicker resolution
            [[runners.kubernetes.dns_config.options]]
              name = "ndots"
              value = "1"

    rbac:
      create: true
      rules:
        - resources:
            [
              "configmaps",
              "events",
              "pods",
              "pods/attach",
              "pods/exec",
              "secrets",
              "services",
            ]
          verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
        - resources: ["pods/exec"]
          verbs: ["create", "patch", "delete"]
        - resources: ["pods/log"]
          verbs: ["get", "list"]
