apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: network-mtls
  namespace: network
spec:
  mtls:
    mode: STRICT
---
