---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/rancher/system-upgrade-controller
  ref:
    # renovate: datasource=github-releases depName=rancher/system-upgrade-controller
    tag: v0.18.0
  ignore: |
    # exclude all
    /*
    # include manifests dir
    !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 24h
  path: "./manifests"
  prune: true
  targetNamespace: system-upgrade
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
    namespace: flux-system