apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pki-service
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - portal
  podMetricsEndpoints:
    - port: 15020
      path: /stats/prometheus
      relabelings:
        - action: keep
          regex: Running
          sourceLabels:
            - __meta_kubernetes_pod_phase
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pki-service
