apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingressgateway
  namespace: istio-ingress
spec:
  values:
    kind: DaemonSet
    podAnnotations: 
      "proxy.istio.io/config": '{"gatewayTopology" : { "numTrustedProxies": 1 } }'
    service:
      externalTrafficPolicy: Local
      type: NodePort
      ports:
        - name: http2
          port: 80
          protocol: TCP
          nodePort: 30000
        - name: https
          port: 443
          protocol: TCP
          nodePort: 30001
        - name: status-port
          port: 15021
          protocol: TCP
          nodePort: 30004
