apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway
  namespace: istio-ingress
spec:
  values:
    service: 
      type: NodePort
      ports:
        - name: http2
          nodePort: 30000
        - name: https
          nodePort: 30001
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway-acme
  namespace: istio-ingress
spec:
  values:
    service:
      type: NodePort
      ports:
        - name: http2
          nodePort: 30002
        - name: https
          nodePort: 30003
