apiVersion: v1
kind: ConfigMap
metadata:
    namespace: monitoring
    name: login-exporter-config
data:
    login.yml: ENC[AES256_GCM,data:pA5XUiVaU6Q/ogwLoebHjO7YUGxpOXrClaySwPnBUzB1Z/GhZEtOh16gZTe6W3tTpKv0VszEE12wZWEKn0GZ/6VgyNOJZ4K1CtwOAtZALdbviKZSrExeXFfkmyyFQ4UtWW4HTaAKF5qfrn2nHH+KyFmFig7B/VKsciU1gRPQ2LNY9eG1PpNOActbZmZnAq86HJtdlAlPanAejYQKBnm7tBCF6OCuRlTXSt/CBQv8gvQuZaynjJsov1dEIZV65pgWEdgPplVUiYepKis0aPOWu8MqTNGeB6WoB5BMykncCrW/THPFHHWj9L3JLK+aNpE2Xuzbiw4ha7WSBcHvOiLmuLo7BdbbnHysbV7XyeH8VQLT8+ycH9lTEwacwDsipwrcaS6rreU9IRyNwh3eUNxlFjfcd7zqJ5IF3SIWC1LRgesqWuoxIGRWkkpVRkgPAMKXQs0GbyZREordOcSokikA2UKuqVkLTpPl5ZldDUe5yXlfsMHlu9sdbR701F9YBqwCOBa6kRWKd98x1AMIWa0Qr64p/J3vS3p4eOrNbOnFBPgdz6kb8Gw4cBLOgLhxahy00u/fmqN60dxSMLSHoJb0h27bTw9aM+nX+QdOTUDYeS8UsJcEbbr17DVptmLf4uS9IGkEhW+djqo70KdGM1MRG4i8Q1I6ARf7JlNO+zAEvLWC5oum6yGHyUwdMJpbGhdu1GezOgRptQFTbjsZ9kYAdNZUQYOV+aOKFFtSUTgR2PL02NF6gQOWozugI8J4Xf1A3k+on0i1n9uRoDGkcY4JLmbh/lqa7Ga1eYGXVppoe3j+gBTSNR3MU/f2oZZfGoI=,iv:BzGqfYQHm0X/MNaQp/Ft5vAz3VnXGRtGU6Lw7a5hicI=,tag:QJJwMu6ufFDPMliNeGmd5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6czZwd0NqVi8yQUQyVjZn
            NTc0L29WeFkxNUEvS3Y4c2c4ZmdSM1BhQzEwCnRPRFZ0SGJPaVEvSjRQNm82Q2Ey
            TU9nZTF2MFIrNjRCNU02ajN1UVVtVGsKLS0tIFk5c2c2YnlSMVJzME95cVpocXo1
            MFBqMW9aWkREK2FaMUxqKzc4UVp6VFUK3N5Itd1k5nW5ZdT7wIO1wYCbqBZpUXwc
            JwUgA87uDAjg+RQrHVyJToctf/ktKlXihZgptQqriCbxhxQLZiZhsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T08:23:59Z"
    mac: ENC[AES256_GCM,data:U5V+i05Y7KOCJqDbYZG7Bi4M+clKYgKa9QZp0ojHzGMXLpg5eAESF+HM9OXx+Y/pu09duT4XKTxRyQ6ZjhmkkFW+9CtApI3ulRHos6lG3+g2tMM6PvMKR2qjNpu+HVpzLHzsYGyekrGfB2Hcek2R0kX8WURD32Lz0zvw8Tpz9wc=,iv:NdTgzHF7CUbHWz7Z9fi3ey43Ia/F/z8fR0FUNTEhI8s=,tag:AmD4OkXNYYsRFkMvRCfrtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
