apiVersion: v1
kind: ConfigMap
metadata:
    namespace: monitoring
    name: login-exporter-config
data:
    login.yml: ENC[AES256_GCM,data:V9i8PYAm/XsIFqFA3a4G11xDpYjoHYaks46GM+TAuK4ButiCC+90NxdahPUqMYIgl3JwRStXetjfLi8C95OWlzWcqKLqxAxwbg1N9mujATE2r6DHKtmce3HmO0IYujt1zhAuha2ygHbyuKY25fh55hgJS8OYrl+sYGfw3/EaXPtjQTjyNZIRW8tfJFMt+ABpIUBlT3XJArMFB1iH+l5+HhrX1IjrQ6yvrUoHRmvwVOOoEROwZJl3raVuqe09T9PTM63lWLV5hBC2R5mGMOpIpiFqbqNNSxw1yr5YT0prH5g171YR9bWGXbu59nPKN18weF5ttED6Vgc8F0j6QHZL3OCsHMkWGT1eiVf7LsnVc9EN8PHMuuEe+ATGNRwSKlUs/2elC7FIOywh6cO2DeoT88SYPm1qr4Tye0Q0Debenwy74whEd6ha5jVtnsuEpuOR9/qkjYAuNg9qpbNR07AIBnfvEU0ldAjXZF1myg9wdFhIHxp2znbH1v8brSZiicj2jIEKgXrK8PHeJxOy+Ltewh0YPez9YAQvHANnAmRMVedroDe9g1GUBWsi3sNmX5LyJejsfgQCy5HInjuht7+OG4J1eynG73AnEKJvxWELbMhLkW0WUz5rB4Mxv7UFN4LlzkB1YXpQG1let5apEhEMCdo8FSEauM/N8+o/btCBtJbhBHtwQlWb1/6DZzZ1e95C2EC9SfC+PLOuG5AAqVf5sIAfFGe9YYDSrzW7MHOzzAsLUaw11DVaXm5XQqbOO4OncehkT/YYFVEbxQEK/2pDjrZKYwAkblxjMhZDQVT5Hb4/+NRM7JOLrI0rsXBkRFMumDVO,iv:9VbcZvjeUnTnO2AKKU32kcf+agr3LWpowRIQ1TFPMa4=,tag:/4Cqt71XCVNLHWy3OWUtqQ==,type:str]
sops:
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U2dPdmhPNTlNdjd6a0VX
            NE0ydEpzM3I4eEIwU0VHMk1TaWptLzdwYmtBCkZUckNSd1FkSEowTmhPWE5TN2RO
            M1g3ZXU3cnFvU2p0RmNTVUdTVmc2cWsKLS0tIFlsMjk3UTk0UFRkUFBIc2k0ekRQ
            U1hlNEozdEd6eE5oWlU1QzZxOGRGK28K+BTc8Q31K3Bm5EC/VnXChMXkK5PimKJV
            UCROQ1f33lYElAPbKeYBw4wAeCcFL86JBsFXQnBH7fcI3rERvzzsLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T19:58:13Z"
    mac: ENC[AES256_GCM,data:ivCeh+k79Ijc71//27zECmczzURHYHUhVjzLcoyOLbcIhtxBCXdkyGpll9DKSsIPo3XrzrcIdCWtYS3WW07lKi5MXw/fLu5wMQF2irvuogODJmhSmGJt78wI6vbnw4TS8CHRJ6p+GDx7lgLqg3WrIZJOmctSzOVYaN7EzHpgfbY=,iv:XxVEsKJcjfuY75Jy5+jYyhtoDu3UMw3d4bfN1FA+9fE=,tag:TJt/8Pc3Xa/QR4Qs2i5hjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
