apiVersion: ENC[AES256_GCM,data:YdI=,iv:prZY9yOmyxAJjIB38fCinSkOnMBxBQaWjldH4lPKN1k=,tag:ulx1PiuXqiX6ypwwaBMflw==,type:str]
kind: ENC[AES256_GCM,data:fLjQ3MLRAzjC,iv:bJ/D9jzyW6AGPL3i83GlTjrq64g1uVFlSuqTerUAVu4=,tag:VnkIE/T7vKLNdA3GaueC5w==,type:str]
metadata:
    namespace: ENC[AES256_GCM,data:xnu3+quKH8XhBQ==,iv:RUT/D1SU3Djtd/gmrYsxScADS6OY5kxuTORvtQtLwgA=,tag:Uxtg5+y5a1d36KHu87a2lg==,type:str]
    name: ENC[AES256_GCM,data:2PbWJbiUaZq7l4X4rPyWrgaVZ06D,iv:5TxXER7e2rguX9goD3lOxfUw0gyRv116KA82wUB7bZE=,tag:4Aj1dTPMmaOPl0sBrlASDQ==,type:str]
data:
    login.yml: ENC[AES256_GCM,data:WodXDH0LWRpaqT9cNQj4tfHpOk0hXoMxrHrXZBUtbhdd0AIC65KG4yXKnngVC9kwaZaS6yDAadVhveBFKuTg0hDHv4jW4zfIPbnWmDm8FT9V71zhRSlK7Tab9n9miGLW9ujuS2/fygdLx+ne3YHc/B7l7rGA/BE0zE93UpETk9MeqEQf+gFLYN0GtlgRhrA8r0eXpLM8xPk2YTKldA3qHeEoDeG7vKtFbBkWKswnUGksPj5yejPL9+RQ8uReiDErRYUcebt1XujhYqFl2gaGGkKzRCAqIPoxKmYgfxp2BPmro76ct1jbwQO3MdMa/rJZxdCHvwE7XqKjN2uz/KkM4uPf1CHCdjtxR02crVfatEusRRWhyS6g6VFA/dkJccATZ+PNWniOVRHbg2kDv/Oll8PP5klBXXmqgTDQ08/u3upHTVFdmZ1Vj0oK80LFuaA0fbFKfEnSkctDn/rJZYcP/BrU5iomupfAvx9IJsv7tJO95lgUKMtLQd2JBmvsex70evpq0wUgroG8DrlaETDuxtXjNxLIt7ns3Ba3XSZNmVhuoqbdo5Za4dgVhxz8gjKyIjQE1dRaYcNHFn/Yy1kJ/MzgTzURm+oLvY/W8AlXL0tIuonNejZO4tdvcBi7Qc/TlwV8ElhH1DvTs0KamU3SnQrMfrn3GebPPfto4hO7RB5mQd+Zf/6wK4vUmYN2TU5vIj3Jt428F7g9gTaWQihwWWX+SFOZs93HpnOYLqDdVfC/PQMU59qJBbGi1fjmuWRjc2s8duR1db9Iez1X29NDo/6ULDkSYHGCl3K9VvA0PzUXML6i8VRUeMm7BhMOLq1LsjSUKgJgN4ahGYBkYfQ3CriaOBc=,iv:NcvSxAchTm3a/YvO3ldGLrEhFRCCko0tWyZaxhgDRt8=,tag:u/ApIfLhTwwg2lEmReRwjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNW44bVo5aGMvaTVnbzNJ
            bG9uMjVvMWwyUmJrSkljZ3lHUGJXOTNTdVEwCktlcExpdGc5a3BIb2hkQzBBY0kw
            aEY5QzlybnJMcXhoVlgweXMveEh3ZFEKLS0tIFlKNkJzZ1g2YTRnbmROUmlkV2lI
            aUx2aFJpSjhPTEhQRmFueGhqTlM3WW8Kz9CzTrRaVc6OCJXdewvgaPx8tjYClwe/
            oLt2s6CNUVpbjSyWPtmBy1e0GTBcIZw7oVX4sWW6IoY9OktHagmGlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T13:51:42Z"
    mac: ENC[AES256_GCM,data:v/q1wYyNZ6qKn/YJ9vbuwLbGg93iWoQ3IATiVbsUNls/uUkqQH3ct9zq1Oj3z646jHMqZLgZMmdMVFmxeRq+/WZ7Si0APT9T+h5ReqA/QoE1NF18gJPTzCX3GfbxcOwgDgbIGLgsaX/WEgB/ePeXUBXThMmCTrzOypEUTrockt0=,iv:FSItcFKTc9Wk5Uhm+p8sc6sGNYnk2dB/EpFA3lXvr4k=,tag:wd/HKzSV9vAPLHORm6Ibvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
