apiVersion: v1
kind: ConfigMap
metadata:
    namespace: monitoring
    name: login-exporter-config
data:
    login.yml: ENC[AES256_GCM,data:z/dXG5j8drnw347H5qkjf6Sh5XeN+fwBJQxD8VxnSLlsfctGe2vCPxmp9D/wGIo+H2udtrnJtPPUVSpg+Dex+UKz8WE0jm5cwwEegBxlNucGtuBw7KjimCcLOpxPZlUkXKSH7KRpWXsMir28v4lecHWASCX6puX74wPAL01X8GU6FG3VKhaMSCatUFKIYIIS/NaC8zC6obrZOqogFzPieF1N6WgvaRKfx7wYqUX5ZjH1AEVsdVo27aK0targZjGxl2pxAkUvRjBG19VxYcE2YEnf8E8rVQI7Fk5+YHv72aoIIRza5GmeysNAiftU9VML0o6hV9DmUTouScrAc2fqfIB7BMKbONEaeM6XU0DI+4PyTRLQTq4G7GWP6Z4cgkOfXs3/sRH3m0LbHI9T5Po+jFxPEbsJ/gOartIkFmdhzrIa4YD3y+kaJZ51ExQl2XiI8s9E7jgJxcEjapne7FH9ZJvuztNx26iQboA3gKMddBkz24M7usqJFukqQvT6LXQaRS44c7IaVHLzIZY0HOiwHNipDyQbW5EpJRjWlvbI5ipy1cI/b8LfeD+f/PHyzMqU4PE9T1ClYxBJ0cfk9v3uC/uj05CuC3gIh6R6/saHAUHmnL3pIZnCY7pBrx9zzwkO6IEuIJS9cYdTbX1PQsUMCPsv2LJhX121X7vV2+R0TXyotaxClpttXThF0gtI9d5JnyaPu3pem68LiQbna4JphORlwk2Q7xdtPpivExXtkzlVhDF0B4ndvLfyb3Vr,iv:CSohY1l8J+fCRhU+Txv8FDsnhgrBOWedvB5BO0YGStM=,tag:HPvtB3R0d+iO0epBaT06Bg==,type:str]
sops:
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U2dPdmhPNTlNdjd6a0VX
            NE0ydEpzM3I4eEIwU0VHMk1TaWptLzdwYmtBCkZUckNSd1FkSEowTmhPWE5TN2RO
            M1g3ZXU3cnFvU2p0RmNTVUdTVmc2cWsKLS0tIFlsMjk3UTk0UFRkUFBIc2k0ekRQ
            U1hlNEozdEd6eE5oWlU1QzZxOGRGK28K+BTc8Q31K3Bm5EC/VnXChMXkK5PimKJV
            UCROQ1f33lYElAPbKeYBw4wAeCcFL86JBsFXQnBH7fcI3rERvzzsLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T11:54:12Z"
    mac: ENC[AES256_GCM,data:ThKUe5gWmk+nN2Jhn12Dcj2mcza/Y1NzgcDZdjMpgfwOTr9j6XeZrePL1bsNk9qoCYSs0QWMVPR7zTbIuBIGxi0xaLk9hN6QaGrCbWvgU7rmeio+Qzqicl9IZqm9Oc+QrmK9NFtVIk03Xc8SsJ0OrfCHTDxwNkNzmLCK8/lm1Io=,iv:pCL9qx52Bxiopo6yqKvhqe8cayEzlAAnUg9D7DyF+O8=,tag:N6wygh2NvcabAwCwvhEWww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
