---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kured
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    metrics:
      create: true
    configuration:
      startTime: "10pm"
      endTime: "2am"
      logFormat: "json"
