---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system-upgrade-plans
  namespace: system-upgrade
spec:
  interval: 10ms
  dependsOn:
  - name: system-upgrade-controller
  path: ../core/system-upgrade-plans
  prune: true