---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system-upgrade-plans
  namespace: system-upgrade
spec:
  interval: 10m
  dependsOn:
  - name: system-upgrade-controller
  path: ./core/system-upgrade-plans
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system