---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 11.7.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        http_403:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            valid_status_codes: [403]
            method: GET
            fail_if_ssl: false
            fail_if_not_ssl: true
            preferred_ip_protocol: "ip4"
        icmp_test:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: ip4
            ip_protocol_fallback: true
            ttl: 64
        tls_connect:
          prober: tcp
          timeout: 5s
          tcp:
            tls: true
        tcp_connect:
          prober: tcp
          timeout: 5s
