---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions:
              - HTTP/1.1
              - HTTP/2.0
            preferred_ip_protocol: ip4
            ip_protocol_fallback: true
            follow_redirects: true
            enable_http2: true
          tcp:
            ip_protocol_fallback: true
          icmp:
            ip_protocol_fallback: true
            ttl: 64
          dns:
            ip_protocol_fallback: true
            recursion_desired: true
        icmp_test:
          prober: icmp
          timeout: 5s
          http:
            ip_protocol_fallback: true
            follow_redirects: true
            enable_http2: true
          tcp:
            ip_protocol_fallback: true
          icmp:
            preferred_ip_protocol: ip4
            ip_protocol_fallback: true
            ttl: 64
          dns:
            ip_protocol_fallback: true
            recursion_desired: true
