---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 10m
  path: ./core/falco
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system