---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 10m
  path: ./core/reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system