---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 10m
  path: ./core/system-upgrade
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system