---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: x509-certificate-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: ./core/x509-certificate-exporter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system