apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway
  namespace: istio-ingress
spec:
  values:
    replicaCount: 2
    autoscaling:
      enabled: false
    service:
      annotations:
        purelb.io/service-group: portal
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway-internal
  namespace: istio-ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: 1.17.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    force: true
    remediation:
      retries: 5
    crds: CreateReplace
  values:
    replicaCount: 2
    autoscaling:
      enabled: false
    service:
      annotations:
        purelb.io/service-group: acme
