apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway
  namespace: istio-ingress
spec:
  values:
    replicaCount: 2
    autoscaling:
      enabled: false
    service:
      annotations:
        purelb.io/service-group: portal
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingressgateway-internal
  namespace: istio-ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: gateway
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    force: true
    remediation:
      retries: 5
    crds: CreateReplace
  values:
    replicaCount: 2
    autoscaling:
      enabled: false
    service:
      annotations:
        purelb.io/service-group: acme
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol-internal
  namespace: istio-ingress
spec:
  configPatches:
    - applyTo: LISTENER
      patch:
        operation: MERGE
        value:
          listener_filters:
            - name: envoy.listener.proxy_protocol
            - name: envoy.listener.tls_inspector
  workloadSelector:
    labels:
      istio: ingressgateway-internal
