apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/hm-edu/portal-frontend:main-70a12fa-1657466294 # {"$imagepolicy": "flux-system:frontend"}
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 80
              protocol: TCP
