---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m
  path: ./core/kured
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system