---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: node-rules
  namespace: monitoring
spec:
  groups:
    - name: Node Alerts
      rules:
        - alert: NodeDown
          expr: up{job="node-exporter"} == 0
          for: 15s
          labels:
            severity: critical
          annotations:
            summary: Node {{ $labels.host }} is down
            description: Failed to scrape {{ $labels.job }} on {{ $labels.host }} for more than 15 seconds. Node may be down.
        - alert: BondDegraded
          expr: (node_bonding_active - node_bonding_slaves) != 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Bond is degraded on {{ $labels.host }}
            description: Bond {{ $labels.master }} is degraded on {{ $labels.host }}
