---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: node-rules
  namespace: monitoring
spec:
  groups:
    - name: Applications
      rules:
        - alert: Systemd Service Crashed
          expr: node_systemd_unit_state{state="failed"} == 1
          for: 15s
          labels:
            severity: warning
          annotations:
            summary: Host systemd service crashed (host {{ $labels.host }})
            description: "Systemd service crashed\n  value = {{ $value }}\n  labels = {{ $labels }}"

    - name: Hardware alerts
      rules:
        - alert: Node down
          expr: up{job="node-exporter"} == 0
          for: 15s
          labels:
            severity: warning
          annotations:
            title: Node {{ $labels.host }} is down
            description: Failed to scrape {{ $labels.job }} on {{ $labels.host }} for more than 15 seconds. Node may be down.
        - alert: Node down
          expr: up{job="node-exporter"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            title: Node {{ $labels.host }} is down
            description: Failed to scrape {{ $labels.job }} on {{ $labels.host }} for more than 5 minutes. Node seems to be down.
        - alert: Bond degraded
          expr: (node_bonding_active - node_bonding_slaves) != 0
          for: 1m
          labels:
            severity: warning
          annotations:
            title: Bond is degraded on {{ $labels.host }}
            description: Bond {{ $labels.master }} is degraded on {{ $labels.host }}
    - name: Update Alerts
      rules:
        - alert: Proxmox Updates Outstanding
          expr: sum(apt_upgrades_pending{origin="Proxmox:bullseye/stable"}) by (host) != 0
          for: 1m
          labels:
            severity: info
          annotations:
            title: Proxmox Updates Outstanding {{ $labels.host }}
            description: Proxmox Updates Outstanding for {{ $labels.host }}
        - alert: Security Updates Outstanding
          expr: sum(apt_upgrades_pending{origin=~".*(s|S)ecurity.*"}) by (host) != 0
          for: 1m
          labels:
            severity: warning
          annotations:
            title: Security Updates Outstanding {{ $labels.instance }}
            description: Security Updates Outstanding for {{ $labels.instance }}
        - alert: Normal Updates Outstanding
          expr: sum(apt_upgrades_pending{origin!~".*(s|S)ecurity.*"}) by (host) != 0
          for: 1m
          labels:
            severity: info
          annotations:
            title: Normal Updates Outstanding {{ $labels.instance }}
            description: Normal Updates Outstanding for {{ $labels.instance }}
        - alert: Reboot required
          expr: (node_reboot_required) != 0
          for: 1m
          labels:
            severity: info
          annotations:
            title: Reboot required for {{ $labels.instance }}
            description: Reboot required for {{ $labels.instance }} due to kernel update
