---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: node-rules
  namespace: monitoring
spec:
  groups:
    - name: Applications
      rules:
        - alert: Systemd Service Crashed
          expr: node_systemd_unit_state{state="failed"} == 1
          for: 15s
          labels:
            severity: warning
          annotations:
            summary: Host systemd service crashed (host {{ $labels.host }})
            description: "Systemd service crashed\n  value = {{ $value }}\n  labels = {{ $labels }}"

    - name: Hardware alerts
      rules:
        - alert: Node down
          expr: up{job="node-exporter"} == 0
          for: 15s
          labels:
            severity: critical
          annotations:
            title: Node {{ $labels.host }} is down
            description: Failed to scrape {{ $labels.job }} on {{ $labels.host }} for more than 15 seconds. Node may be down.
        - alert: Bond degraded
          expr: (node_bonding_active - node_bonding_slaves) != 0
          for: 1m
          labels:
            severity: warning
          annotations:
            title: Bond is degraded on {{ $labels.host }}
            description: Bond {{ $labels.master }} is degraded on {{ $labels.host }}
