apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-eab
  namespace: portal
  labels:
    account: eab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-domain
  namespace: portal
  labels:
    account: domain
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-pki-rest
  namespace: portal
  labels:
    account: pki-rest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-pki-internal
  namespace: portal
  labels:
    account: pki-internal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-dns
  namespace: portal
  labels:
    account: dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-dcv
  namespace: portal
  labels:
    account: dcv
---