apiVersion: apps/v1
kind: Deployment
metadata:
  name: pki-rest-interface
  namespace: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pki-rest-interface
  template:
    metadata:
      labels:
        app: pki-rest-interface
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readonlyRootFilesystem: true
      serviceAccountName: portal-pki-rest
      containers:
        - args:
            - --audience
            - "https://api.hm.edu"
            - --ssl_service
            - "pki-service:8081"
            - --smime_service
            - "pki-service:8081"
            - --domain_service
            - "domain-rest-interface:8081"
            - --jwks_uri
            - "https://sso.hm.edu/idp/profile/oidc/keyset"
            - --cors_allowed_origins
            - "https://pki.hm.edu"
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: pki-backend
                  key: sentry_dsn
          image: ghcr.io/hm-edu/portal-backend/pki-rest-interface:main-af89f08-1761328280 # {"$imagepolicy": "flux-system:pki-rest-interface-policy"}
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-rest-interface
  namespace: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: domain-rest-interface
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
      labels:
        app: domain-rest-interface
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readonlyRootFilesystem: true
      serviceAccountName: portal-domain
      containers:
        - args:
            - --audience
            - "https://api.hm.edu"
            - --jwks_uri
            - "https://sso.hm.edu/idp/profile/oidc/keyset"
            - --db
            - "postgresql://pki:pki@postgres.portal.svc.cluster.local/domain"
            - --preseed
            - "/data/data.json"
            - --ssl_service
            - "pki-service:8081"
            - --cors_allowed_origins
            - "https://pki.hm.edu"
          volumeMounts:
            - mountPath: /data
              name: domain-data
          env:
            - name: ADMINS
              valueFrom:
                secretKeyRef:
                  name: domain-interface
                  key: admins
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: pki-backend
                  key: sentry_dsn
          image: ghcr.io/hm-edu/portal-backend/domain-rest-interface:main-c9d7290-1761110283 # {"$imagepolicy": "flux-system:domain-rest-interface-policy"}
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: domain-data
          configMap:
            name: domain-data
            items:
              - key: data.json
                path: data.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eab-rest-interface
  namespace: portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eab-rest-interface
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
      labels:
        app: eab-rest-interface
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readonlyRootFilesystem: true
      serviceAccountName: portal-eab
      containers:
        - args:
            - --audience
            - "https://api.hm.edu"
            - --jwks_uri
            - "https://sso.hm.edu/idp/profile/oidc/keyset"
            - --db
            - "postgresql://acme:acme@postgres.portal.svc.cluster.local/eab"
            - --acme_db
            - "postgresql://acme:acme@postgres.portal.svc.cluster.local/acme"
            - --provisioner_id
            - "acme/acme"
            - --domain_service
            - "domain-rest-interface:8081"
            - --cors_allowed_origins
            - "https://pki.hm.edu"
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: pki-backend
                  key: sentry_dsn
          image: ghcr.io/hm-edu/portal-backend/eab-rest-interface:main-c9d7290-1761110293 # {"$imagepolicy": "flux-system:eab-rest-interface-policy"}
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pki-service
  namespace: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pki-service
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
        prometheus.io/port: "2222"
        prometheus.io/path: "/"
        prometheus.io/scrape: "true"
      labels:
        app: pki-service
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readonlyRootFilesystem: true
      serviceAccountName: portal-pki-internal
      containers:
        - args:
            - --db
            - "postgresql://pki:pki@postgres.portal.svc.cluster.local/certificates"
            - --enable_notifications
            - "true"
            - --smime_key_length
            - "4096"
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: harica
                  key: user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harica
                  key: password
            - name: TOTP_SEED
              valueFrom:
                secretKeyRef:
                  name: harica
                  key: totp_seed
            - name: VALIDATION_USER
              valueFrom:
                secretKeyRef:
                  name: harica
                  key: validation_user
            - name: VALIDATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harica
                  key: validation_password
            - name: VALIDATION_TOTP_SEED
              valueFrom:
                secretKeyRef:
                  name: harica
                  key: validation_totp_seed
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: mail_host
            - name: MAIL_BCC
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: mail_bcc
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: mail_from
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: pki-backend
                  key: sentry_dsn
          image: ghcr.io/hm-edu/portal-backend/pki-service:main-941b244-1761125697 # {"$imagepolicy": "flux-system:pki-service-policy"}
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 2222
              protocol: TCP
          readinessProbe:
            exec:
              command: ["/grpc_health_probe", "-addr=:8081"]
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: domain-rest-interface
  name: domain-rest-interface
  namespace: portal
spec:
  selector:
    app: domain-rest-interface
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pki-service
  name: pki-service
  namespace: portal
spec:
  selector:
    app: pki-service
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eab-rest-interface
  name: eab-rest-interface
  namespace: portal
spec:
  selector:
    app: eab-rest-interface
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pki-rest-interface
  name: pki-rest-interface
  namespace: portal
spec:
  selector:
    app: pki-rest-interface
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
