apiVersion: v1
kind: Secret
metadata:
    name: domain-interface
    namespace: portal
stringData:
    admins: ENC[AES256_GCM,data:YfCFqIN/jEh7pe7SGHcaK6I4jrNQ9N+T72C99yB4yU2hLeTFz3T2hqYted/fG86BB2ZjnHZrtiuwPNLd9LDkFJUhPVt7FRn5mXmVfGG+d7O0eEvvssb64tGiRX+hhEiUoBAaI94acjNDKduCg9/d3PuwWA==,iv:XTsg4qSz5kZAmwusXDxKdhBKybvFjBwoPo3mhz/S65Y=,tag:UuAr5v5gLHGsi1ye1CZZJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNjJITUtGWDRwK0s1YnB1
            eUNNakVuWVk2cExyOWNIdnU5Q0VCdktIMWdZCkFMV2IwbGptcVg5U0ZVaGloekI4
            R0tLWWltWm92QmV5aVE3ZlBSbE96RlkKLS0tIEFQWGtBcFJhMmIrMFdJb2Y3L1lo
            L1FQSlp0OGlRV0ZvSTZQRWI3dFAxREEKyFlaggr58kS922ED9MyYNwkW9W5e8/hb
            iRUgBMvWGEGO/1df1xivzc0qxXEbGOeCXZh85XsltYFD+l8NX5o+1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T11:56:19Z"
    mac: ENC[AES256_GCM,data:WSrk7ZRqLXpksxa0/KR89AfIKifF0zkjNbimEBr/lu4uJU5QghZ9+G7nRLzbOh4UakumvuuQUpXh+g4uSjHwdFFZLgwTs3Ta7A+4IW1aLEb2VbQRA/6xFYULBmnmq3OJtR3mlPdM263TKF0zRf2GX/6NytglFZvbYKunBKYrTZ8=,iv:xA4G8SvxQg/opfFKhmEX/ndW75pHey7hgohi/rkRf2I=,tag:O1rOFHI7drzLFEhWsCKCBg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pki-backend
    namespace: portal
stringData:
    sentry_dsn: ENC[AES256_GCM,data:fzZ7I74Svl8D5miyYFtlByysTCkzF5HbIWxxnuP+o6pQAt8MOlrNwnZ8v31rLlA/RLB5MAKP7CNV,iv:/eAHAN9kqNOE/codLv6xXqTv5jsSjw2AzZtu0ANXoTs=,tag:Buyi4yp9FsGjZXRwCmuBBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNjJITUtGWDRwK0s1YnB1
            eUNNakVuWVk2cExyOWNIdnU5Q0VCdktIMWdZCkFMV2IwbGptcVg5U0ZVaGloekI4
            R0tLWWltWm92QmV5aVE3ZlBSbE96RlkKLS0tIEFQWGtBcFJhMmIrMFdJb2Y3L1lo
            L1FQSlp0OGlRV0ZvSTZQRWI3dFAxREEKyFlaggr58kS922ED9MyYNwkW9W5e8/hb
            iRUgBMvWGEGO/1df1xivzc0qxXEbGOeCXZh85XsltYFD+l8NX5o+1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T11:56:19Z"
    mac: ENC[AES256_GCM,data:WSrk7ZRqLXpksxa0/KR89AfIKifF0zkjNbimEBr/lu4uJU5QghZ9+G7nRLzbOh4UakumvuuQUpXh+g4uSjHwdFFZLgwTs3Ta7A+4IW1aLEb2VbQRA/6xFYULBmnmq3OJtR3mlPdM263TKF0zRf2GX/6NytglFZvbYKunBKYrTZ8=,iv:xA4G8SvxQg/opfFKhmEX/ndW75pHey7hgohi/rkRf2I=,tag:O1rOFHI7drzLFEhWsCKCBg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: mail
    namespace: portal
stringData:
    mail_bcc: ENC[AES256_GCM,data:Bi6fM5oIx704hwSeww0Vll56,iv:Erd7chZcmLmfBOfxlMLVFzXbjc8B3DfRMn+MOgYdfUY=,tag:3lOOMU5BPVta44ihwKWF+Q==,type:str]
    mail_from: ENC[AES256_GCM,data:+MVuwctbm4Rm5XO9FWE=,iv:i+rF5vMuLfG3BlZucyokko1zODr79h6VNm6fwoWhBq0=,tag:2BnBUyUHRQxsGFMK0nm0GA==,type:str]
    mail_host: ENC[AES256_GCM,data:q5U+zXYWP5de8ANwEgQ=,iv:WW0t+kQ1qh6XuhNHpOMhUxm07kSOQEj6pFi9Xh/KhrM=,tag:Y5ejudn9YCkYZ59i0vfo5Q==,type:str]
    mail_username: ENC[AES256_GCM,data:XkKgLihoOMQbeVZ3nCE=,iv:oEkHbjuve2slCfabLnpWv0sfsRqmYAyML2tjTx1eofo=,tag:7+p3MmTmvQjMzKrLMYwmhg==,type:str]
    mail_password: ENC[AES256_GCM,data:myL+xdG5S60LKaf+6w00Jyi3dBnmNakJ8dr7LVe1qQNrifgFYklysLtxJtkftA==,iv:6jrcsww3iROuPRMifJVZJaupb7/CdhIwXnySD/pfNog=,tag:8D0tWCBxxUBFkKL0+GsHVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNjJITUtGWDRwK0s1YnB1
            eUNNakVuWVk2cExyOWNIdnU5Q0VCdktIMWdZCkFMV2IwbGptcVg5U0ZVaGloekI4
            R0tLWWltWm92QmV5aVE3ZlBSbE96RlkKLS0tIEFQWGtBcFJhMmIrMFdJb2Y3L1lo
            L1FQSlp0OGlRV0ZvSTZQRWI3dFAxREEKyFlaggr58kS922ED9MyYNwkW9W5e8/hb
            iRUgBMvWGEGO/1df1xivzc0qxXEbGOeCXZh85XsltYFD+l8NX5o+1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T11:56:19Z"
    mac: ENC[AES256_GCM,data:WSrk7ZRqLXpksxa0/KR89AfIKifF0zkjNbimEBr/lu4uJU5QghZ9+G7nRLzbOh4UakumvuuQUpXh+g4uSjHwdFFZLgwTs3Ta7A+4IW1aLEb2VbQRA/6xFYULBmnmq3OJtR3mlPdM263TKF0zRf2GX/6NytglFZvbYKunBKYrTZ8=,iv:xA4G8SvxQg/opfFKhmEX/ndW75pHey7hgohi/rkRf2I=,tag:O1rOFHI7drzLFEhWsCKCBg==,type:str]
    version: 3.13.2
