---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gateway-apis
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubernetes-sigs/gateway-api/
  ref:
    # renovate: datasource=github-releases depName=kubernetes-sigs/gateway-api/
    tag: v0.5.1
  ignore: |
    # exclude all
    /*
    # include manifests dir
    !/config/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gateway-apis
  namespace: system-upgrade
spec:
  interval: 24h
  path: "./config/crds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-apis
    namespace: flux-system
