apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 15m
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      version: 1.66.4
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
    crds: CreateReplace
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
   apiServerProxyConfig:
    mode: "true"