---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m0s
  url: https://github.com/tailscale/tailscale
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include chart dir
    !/cmd/k8s-operator/deploy/chart