apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:/l7CuY2pTfBNuO5s,iv:fZWnbDxvJgCtdCKA+Y6ctoq3PgxF+sMmp31GRcM324k=,tag:sBC1Z0AXsmzpyDbvSWeO2g==,type:str]
    client_secret: ENC[AES256_GCM,data:sT860Fw9bWhraUTnyCI9wYdYFqImAUCMEe5InMEhGhWsXBIuyeHtxrg/+OY2u0c2v9WsjrpEWrt40Q==,iv:zlwrrST+zex8BSsNRkZvnXtp/qvUGZzhLnLBgwbFQvY=,tag:C67zAYnJKCPU2t4+CT+ioQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MHBkbFkza3hVcTFuUjg2
            bnIyaWw1T1dMdEY2d0pMdW5NRUNoQmtKTVIwCnd6L1F2SFJ0S3RKdlMzRDk2dEho
            Z2ZjMTVKTkIvNlVkdzQ4cGpGNVhBZEkKLS0tIEhmTkhWUURPbDVJVE94eFNKdk82
            dHNkckdHdlArbldObExqTVNWWVEzUGsKnDUHZKD9pAmmh+QXeCI/3alZV8q59+oE
            sVPai5ZFokmrHiU3l64t9m4PW/MCWOoIA0CNKmVApbd5Bj6AsTvv3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-02T17:36:37Z"
    mac: ENC[AES256_GCM,data:Xi3gS0z85IlSug581MOXdofIom95HW4VNoEibxida48pA6cQTUUCtM8DisemgeaQ7KtgZ8ZM/G7sTljql0b6L2s8izmNM8bL2f+gASfIHrlw/PA66gIzPELcvnOvnQn41hPxNehe2Z1DX/CuKRR3+d6xpmZ4ok7RSbITuv+skiU=,iv:lNz+qoYPn9HFEKHs8IqdDr5uncDsG+QUk0w/GWC99QU=,tag:P3MocZ32kyyUATFeF8bakQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
