apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 15m
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
    crds: CreateReplace
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    search:
      # -- Enable Tempo search
      enabled: true
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftHttp:
          enabled: true
        thriftCompact:
          enabled: true
      opencensus:
        enabled: true
    serviceMonitor:
      enabled: true
    minio:
      enabled: false