apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-agent-shibboleth-stage
resources:
  - namespace.yaml
  - gitlab-agent.yaml
secretGenerator:
  - name: gitlab-agent-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
