kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: portal
  name: cert-nfs-pv-claim
  labels:
    app: cert
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: portal
  name: cert-config
data:
  ca.json: |
    {
      "address": ":8080",
      "publicAddress": ":80",
      "commonName": "acme.hm.edu",
      "dnsNames": [
        "acme.hm.edu"
      ],
      "logger": {
        "format": "json"
      },
      "db": {
        "type": "postgresql",
        "dataSource": "postgresql://acme:acme@postgres.portal.svc.cluster.local/",
        "database": "acme"
      },
      "authority": {
        "type": "sectigocas",
        "provisioners": [
          {
            "type": "ACME",
            "name": "acme",
            "requireEAB": true
          }
        ],
        "template": {},
        "backdate": "1m0s",
        "config":{
          "pkiBackend": "pki-service:8081",
          "eabBackend": "eab-rest-interface:8081"
        }
      },
      "tls": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        ],
        "minVersion": 1.2,
        "maxVersion": 1.3,
        "renegotiation": false
      },
      "storage": "/opt/step",
      "managementHost": "eab-rest-interface:8081",
      "validationBroker": {
        "host": "validation.pki.hm.edu",
        "username": "server.hm.edu",
        "organization": "hm"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificates
  namespace: portal
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: certificates
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
      labels:
        app: certificates
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readonlyRootFilesystem: true
      serviceAccountName: portal-acme
      containers:
        - image: ghcr.io/hm-edu/certificates:master-8bf35d9-1723132886 # {"$imagepolicy": "flux-system:certificates"}
          imagePullPolicy: Always
          name: app
          command: ["/usr/local/bin/step-ca"]
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /opt/step
              name: cert
            - mountPath: /home/step/config
              name: cert-config
          env:
            - name: STEP_TLS_INSECURE
              value: "1"
            - name: STEP_LOGGER_ONLY_TRACE_HEALTH_ENDPOINT
              value: "true"
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://tempo-distributor.monitoring:14268/api/traces
            - name: DNS_RESOLVER
              value: "129.187.244.11"
          envFrom:
            - secretRef:
                name: acme
                key: MQTT_PASSWORD
      volumes:
        - name: cert-config
          configMap:
            name: cert-config
            items:
              - key: ca.json
                path: ca.json
        - name: cert
          persistentVolumeClaim:
            claimName: cert-nfs-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: portal
  name: certificates
  labels:
    app: certificates
spec:
  type: ClusterIP
  ports:
    - name: acme
      port: 80
      targetPort: 80
    - name: internal
      port: 8080
      targetPort: 8080
  selector:
    app: certificates
