apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: certificates
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: certificates
  filterTags:
    ## use "pattern: '[a-f0-9]+-(?P<ts>[0-9]+)'" if you copied the workflow example using github.run_number
    pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---