apiVersion: v1
kind: Secret
metadata:
    name: acme
    namespace: portal
type: Opaque
stringData:
    MQTT_PASSWORD: ENC[AES256_GCM,data:i37RTAuF/Yb3AuKQxE4/SHJZBeOd0BXt6nzUOFIoH/M=,iv:Q5HzjG7iSgGj5YjItzoEncn2nrLNf6bv2aM7X/Ec1/w=,tag:8QAPVonk2Vbg8j3xKwJqDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUU1EKzBNZ1lRSEtwS1Ry
            RGY2aTdMK0xhSEN1djdxMHJ5MXZmdTcxaVRzCkdpUUpzaERObWdmSW5OZis0eG1t
            clNyeWZnOVBpSndSTGFUMTJEUGFYQjQKLS0tIHBQTHkvTlk0SUZBQ051b2FrcDBm
            Tnl2L3dQbm5FRW5yaWxucDFrdW9aMncKkUSzCWN6WejDtzallnZAs6CySCa7KPHc
            93fyisU7YEQo6mgmEsPV/Defq7f041qte2xRMwZfXBVG9vf2hPIxQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T04:38:18Z"
    mac: ENC[AES256_GCM,data:2hppi4RdO3VWYHnUJSL1hrRkiEK8TKjCI+zJtQEjTsZgPmVt3xeqy+FWvO9dQkst0tnhJ+IVMKy279pOf9WalVkNnVcccHmz7VBfKWlyw7CCTOTV8WcP1/x3Naf9B7QvP5yI+omwyRq2YWzOH6K+z2apvZwDkPI0dKy+i+UNBjw=,iv:YcbPJ/MoQORnOYP7BCyfieAY8W8ouap20MsZtLwwAgI=,tag:dpinCISiWZ7u4b1s+N3fxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
