---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - kured.yaml
  - istio.yaml
  - prometheus-community-charts.yaml
  - grafana.yaml
  - longhorn.yaml
  - cert-manager.yaml
  - minio.yaml
  - vector.yaml
  - bitnami.yaml
  - nfs.yaml
  - gitlab.yaml
