---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.17.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  valuesFrom:
    - kind: Secret
      name: thanos-values
  values:
    receive:
      enabled: true
      service:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/tags: "tag:k8s,tag:k8s-monitoring"
    query:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      replicaLabel:
        - __replica__
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
    queryFrontend:
      enabled: true
      replicaCount: 2
    bucketweb:
      enabled: true
      replicaCount: 2
    compactor:
      enabled: true
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 90d
      retentionResolution5m: 180d
      retentionResolution1h: 360d
      persistence:
        enabled: true
        size: 10Gi
    storegateway:
      enabled: true
      replicaCount: 2
      persistence:
        enabled: true
        size: 10Gi
    ruler:
      enabled: true
      replicaCount: 2
      replicaLabel: __replica__
      alertmanagers: ["http://alertmanager-operated.monitoring.svc.cluster.local:9093"]
      persistence:
        enabled: true
        size: 10Gi
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
