---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.13.13
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  valuesFrom:
    - kind: Secret
      name: thanos-values
  values:
    query:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      replicaLabel:
        - __replica__
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
      replicaCount: 2
    compactor:
      enabled: true
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 90d
      retentionResolution5m: 180d
      retentionResolution1h: 360d
      persistence:
        enabled: true
        size: 10Gi
    storegateway:
      enabled: false
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
