apiVersion: v1
kind: Secret
metadata:
    name: thanos-receive-http-config
    namespace: monitoring
stringData:
    config.yaml: ENC[AES256_GCM,data:KPhiGWAFK9olo3Fd5xGbZwkf2yvDwyvB0hkOY9qER24b+fPWwAxKq+muZdYxjRSeox+wQ3qNh4PgkJfnCTKpE7EgOqE+s2XwHKcBWOYWxOmWa7J7VSbat7q502B47Z4=,iv:FzomQy6ve7jzTzkce6IUTRWHvTIlXZykt2YtIqP5TUA=,tag:+AieuzWR139Kik4z/KgUdg==,type:str]
sops:
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eHUxTGl3ak9Scy9yVXBk
            Qy9ZNXF3OVNLMjFSdUtMZXlQbHd4U2VOQzFJCmUvV3ZmR3RZM1NDbkR1Y1orUE1y
            WC9TRElwUXc1NmdoOUdZRHRDb245U0EKLS0tIGlkUjMwNTdnekk3N1ExTjdXRkh1
            SHl6VTluRW5ZQjFnanJyZTM5ZTdNWWcKS1kkGqrwwwZZpJ4F8IyG64zT82+nXl4q
            eOe8QGN4nD7H7Mk6QD7HyqAWMjK9BbrU+TL+GzbaoHAQYmcf2J7xUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T16:39:24Z"
    mac: ENC[AES256_GCM,data:8AcmuPaKnidlLafagB6Cbf48F6NFD3BQu1wsP6kjERm4bApQRlLkfNXqToIk/2zcm72ow78r/WWM7jdlzCaMA9DBkKg3Xsn1xSDZZtKqZ6lc/dWsb4HNY3OOpKuVQzlidV4M4gT+54cbA8NF2yx0iLgW90BLwrFNj1/D0wsZK0g=,iv:osbFpYPKfFU5F2Bswbek5+u1pwosX3c5oBd3+YPYrYY=,tag:R9t4ReUZVgejsaK+ysZ74w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
