apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-workspaces-proxy
  namespace: gitlab-agent
spec:
  interval: 15m
  chart:
    spec:
      chart: gitlab-workspaces-proxy
      version: 0.1.12
      sourceRef:
        kind: HelmRepository
        name: gitlab-workspaces-chart
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: gitlab-workspaces-values