---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab-workspaces-chart
  namespace: flux-system
spec:
  interval: 1h
  url: https://gitlab.com/api/v4/projects/gitlab-org%2fremote-development%2fgitlab-workspaces-proxy/packages/helm/devel
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-workspace-proxy
  namespace: gitlab-agent
spec:
  interval: 15m
  chart:
    spec:
      chart: gitlab-workspace-proxy
      version: 0.1.9
      sourceRef:
        kind: HelmRepository
        name: gitlab-workspaces-chart
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: gitlab-workspace-values