apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-agent
resources:
  - gitlab-proxy.yaml
secretGenerator:
  - name: gitlab-workspaces-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
