apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-proxy
resources:
  - gitlab-proxy.yaml
secretGenerator:
  - name: gitlab-workspace-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
