auth:
    signing_key: ENC[AES256_GCM,data:1y/3VxZt1gfI0xXhFk933D1HHX+zEvM2rurhuS3UHFfXQW0eG5hoyxCd,iv:T5dh39spHDQ/ULe+3LakH8BIfnyy5C8ZFYdfb+zSu9I=,tag:2+WIpRsWgdozxRCklKPt1g==,type:str]
    client_secret: ENC[AES256_GCM,data:4ugyR1fSnwxFL8p20SxtUnyg0JKnWzLsjGaGxjKeiH8Vw7Mud1M8MoJLH25byUXb1hZygsonAEcbcCenlY7ekrt/PZUvkA==,iv:+Rc/u6vyEZEZ0lWhRx8JJQbNynJTrT7jWQ/NGBbLWaY=,tag:JgQuq/Nc+l8MtYVc+bwPYA==,type:str]
    client_id: ENC[AES256_GCM,data:dl3nOpemYf4u/Gao11owiB2xo5i5P9U4Cq9uM0glXUE3u1F628AemwlLce9zJzws80ldJR7DpRfkaW3+6xl5tA==,iv:4qAnRuWsA/dGkCJHu8nv17NO8Nsochi3Hqh9emhc20I=,tag:pyybDLTOSP8jjO38Nase9A==,type:str]
    redirect_uri: ENC[AES256_GCM,data:XtbgQCIn9AN+aeGVicyTUVUXk/tymXW4s0TPImnBom9nPg9M7fWvSQq2,iv:iF9HlJJI7yMgz9R+hLiNI5HBtboZjQir4QKVeEhyvcI=,tag:tKbj6lKfJlnYGkk/piouaA==,type:str]
    host: ENC[AES256_GCM,data:ExlsXZOY+BnLWDC0V/9rasx4Wn6D,iv:KfDlecNTZobQm5k0Wu2N5gDZNqPHIts8FRUbut/+osk=,tag:etuwlXQGgS2/T46LfEwo4A==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:x8mzlP4=,iv:S94M/sMxACiqR83yt9wJctpraIOInisSXT8e2K8wfqk=,tag:vfgLL7BGJODYUqkJjwTXUw==,type:bool]
ssh:
    host_key: ENC[AES256_GCM,data:oCQ+SxVFSgSxxql49tZe+0O8Zw1QcSN/2sdz9ktpskft7owG+p4Uaa4jPa9imTrqlKyvXHfC543zw0gCKx4481H8oXi2G9mcqZDaFRWlA5/tL2Yg4tq+ShCHbOXt6YQB5GwJsnwYReSaP2LU3w9r9ZlsxPqHWocEyz1oWaBWMuxrAdJG6hjCWFL+DdfDCk+XIvAPyhkjxxTV1+fw+ECwnVZtQuL4d6ddhVJZQ2YkDSrqSFjjInqak9UD+P3i2Rj/i4yh/lBxUJK1SGOpUVxRo4cQx5xJHHRPG3j5FWUJIQcLNz4JUNVqzAN/5yMblxdfcY6JQqNxfMEZjwxl/PGv76QU7hS5wJ6CbqsND9JOnKumMfSCDmiLjPjF+w/lmz/onsYVpgiYMo42ygUfOlDr7OC3ehN+cdXfl/Hp87j8Ujj4RXl6YqbIUp4M5u9hQLcu2hN+jdKbknvmNx1GV96d3m8EN1J1AdmT1BCRMajGHSRq7hh9LdDMIU3m1f9PT1FxJR1cbpmvBAIkEX/orsA4c0JTi221OFiPewAk9jjwGBYyeR0=,iv:KnYtu1NVvpub/Xm5HwnfVHRoI9eeHHAyqyVvekBJATE=,tag:Tud1lz5uE9PxONNQ9ptD4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicjQ0TWgyaVY5dHRoY04w
            WFRwSW5CdDBPakJXOTRHRFlMbVAvNXRTWmxVCkd2WHlVb1NHYWxCQi9KZk5XU05T
            eHhsVHV3NXc3OE8wSmI3NHF5eVd2TWsKLS0tIFIyZmQyK1dOOEhuVlNmUWNhazRY
            WXRmd2h4UDVnQXpaSWpjVDNINkRlZU0KO4I/DKh4RIKkOmTvO5OJFBK5QVeEmQ9j
            s0WOSzrrb5YnXswqMRU9uXT9pj8wBzmkYKTiSpL540sbODi/pzUdbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T17:37:11Z"
    mac: ENC[AES256_GCM,data:f7K3PyM8zJbJNZ7NJ5UK5xTwEAtalpE4rpysqomwJK6jRSxD+J78gvyZc42jzwp5PitbvF1+HFsh8zNu8Dit6BbK3K9j/Ehmc7LD0irh+A63afVSoY+JIdPJMEYGqtEb4rwid92ZSvuaFJOJekEAKr8JR1F8eGaaHcdb0FsDkTg=,iv:GRc4j9M3w/Wf9+Bbd/plqpAXOdiUuJFuWaemDUncgac=,tag:1dlDrjQjnfNr+AaG/ybveA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
