auth:
    signing_key: ENC[AES256_GCM,data:UXMj6NLhQfWP+EN2hCIAi6TiKpNUhy6wR9p3hqbyWHguq1x5LwxB2hEb,iv:0PadRBwvwIfd6ZN5o3wqBAPxusfIiqaiOetbj6pjdBs=,tag:BT9Dyc4/3e70BYEY091k5A==,type:str]
    client_secret: ENC[AES256_GCM,data:MGmsMoutPYzMfaux+neRwcod66H+LQAm6xhK84suCb251vmMykxhHo/67VL3HDfECvqyh2yW/XNNV+KAm8zUPlCu/oQtAA==,iv:gOKVdV20yxGVZZYzIXv9DrGGNyG4Icdq5XBiLzLVeyw=,tag:nbYU4s0+heTgud9pGNAu7Q==,type:str]
    client_id: ENC[AES256_GCM,data:YeImiwvdr80DDS9NoE6flzsLXt3U8w5ARc8GnI9KcElhGBFvSx8AyQdJggv1rW/hvGl2UBj5vi2HGgHRXiYhLg==,iv:uW4pW7/AW+kigb5gOzQF/ZXus2qzwAZnJlpxmQlDkZY=,tag:XmhPTcSK8bjFrwIE6yM16A==,type:str]
    redirect_uri: ENC[AES256_GCM,data:o9htQsyaRAkGqGibbQNwribB21hJeZP7co70MZ8RMLtJaCzAU53v1pkt,iv:1r8sjEzoYtyig/8iFK5cdq1+mgnqNwb0Z80z/Rd8oG4=,tag:C6mrfwxHJAgGRVmjnDgpQA==,type:str]
    host: ENC[AES256_GCM,data:uaEmTKpNwxnVA+z0RZj54H53wGAY,iv:tDd6krwF1fkllENif/JBPGOIlv4cmzUoZ1Dc4yKp1Ho=,tag:OSQVBPNOHFYyr5IgV/M00w==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:xGsCiZQ=,iv:K8zUvho//F3veg5K6btbuaxAUJBAa8sFhUbjX1SZtKM=,tag:Ta+3lUoQscWsVLtUsNDWFA==,type:bool]
service:
    ssh:
        type: ENC[AES256_GCM,data:UXfFsQYoe7Qa,iv:YYfTlGOsQi0439S6CrcjrrlYBd1Bn9v33NRaUjIQA4g=,tag:GUesate3B8aGwWpNThRKNw==,type:str]
ssh:
    host_key: ENC[AES256_GCM,data:oNbh5zMy2foNTKIB08SU+cEYIK0DBp5vbbHgbwbA+fhqKYcpv+iPV2R7fbClT7S4SBoyBDCUezAND6eFApDpmQqgHn6tP/7iNvN1Aao5uXJnLbSt92wFptHmRTLoro8nUtAQEQVMSWl8/9/sM/1CZmbb56Io1PD7+LMf0soWLXNF7sKQOOB1bz6LA6ay4LcrX2GZ6olTLsKVTaSO+yopEtvtAOohzXAs576VpMjRdh/JCnE0nL3cf+J7dOH3nvEHPGJOzt5lGe81RzTqeJh3CLejJ4V6J2G+ncu41r1M88s16zpLJjeIG/leZ0gkgkOBrCMF7EbnLX1gurZnUGk+vLLVjvmSo7StT6kSnLl0JNa//j38IWC2qBt6aDVpJGwFzDZfz5kszJ+e8mLPuzyCP15y77PnfyUbCqiqdj1BdCNZRNGj8yznYXKUxG4JxMPNFIz0RqZ9OkCqihUaNROBnKkUqUOMxl8r3L60NVOlbzDtx9PXkXb3rlwMbcxtc/zifJU51W/fqz8zdj4KriQGTZT1fdUiMyClkL+NyCLxjAcn5LE=,iv:uQBiJwI8wAgAuQYQQKG9mAXlo7CoLcSdzgL5wDRj0CE=,tag:6jLz4Y6NkTWzgm4CJGruRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQVNtWWJlRVdvTkxXK0V4
            RXpGaDA2S3ljSE1jUGprTlU1em52SG1xaEJZCkdvMzlCanNmeEtsOHdCdWtTRkNh
            SnQyWHhPbmVsZFRPOHJDQVloV21UcmsKLS0tIGdpNVZsSUdkNVpuWEREb2RQakZD
            QmVSOXFGQ1VUMFRJZWxsNGFsMWdZYzAK5ERgjkxS3BylP0tNjAfa4xdeYF28c4zn
            2dvheS3wrYCfxl4rcVXE8hE5kkKhfpmNK/Rc/VQwyg21ZQgV//QdHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T18:13:00Z"
    mac: ENC[AES256_GCM,data:A3t2rzwJktHgHfnmvn4iM2E/Y9IX3b1o5C8xwXEgyxtwgsZ7nsHVRD10yyzdyfxLNKqvd1glwDJZr3mecV9pYXUVqPzWNRx9f8jpgjMkY7zdfynU08ZgTHBPiYHIMgAtnBfiwyYFrMf2B2danqmCaezuqKwSoNPYPZFX8Y6BYvc=,iv:zTlmTbcJ3siFLGXRYNuarfPHwB5QZ5VSfQh/5UiOByE=,tag:5VBywraHcYh3W+LuauL3Qw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
