---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 15m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.64.1
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: gitlab-runner-values
  values:
    gitlabUrl: https://git.it.hm.edu
    runners:
      secret: gitlab-runner-secret
    rbac:
      create: true
      rules:
        - resources:
          - pods/attach
          - pods/exec
          verbs:
          - create
          - patch
          - delete
        - resources:
          - pods
          - services
          verbs:
          - get
          - watch
          - create
          - delete
        - resources:
          - configmaps
          - secrets
          verbs:
          - get
          - create
          - update
          - delete
        - resources:
          - serviceAccounts
          verbs:
          - get