---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 15m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.75.1
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: gitlab-runner-values
  values:
    gitlabUrl: https://git.it.hm.edu
    runners:
      secret: gitlab-runner-secret
    rbac:
      create: true
      rules:
        - resources:
            [
              "configmaps",
              "events",
              "pods",
              "pods/attach",
              "pods/exec",
              "secrets",
              "services",
            ]
          verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
        - resources: ["pods/exec"]
          verbs: ["create", "patch", "delete"]
        - resources: ["pods/log"]
          verbs: ["get", "list"]
