---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 15m
  chart:
    spec:
      chart: gitlab-runner
      version: 0.49.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    gitlabUrl: https://git.cc.private.hm.edu
    runners:
      secret: gitlab-runner-secret
      config: |
        [[runners]]
          pre_clone_script = "for i in $(seq 1 5);do getent hosts gitlab.lrz.de && break || sleep 1;done"
          [runners.kubernetes]
            helper_image_flavor = "ubuntu"
            namespace = "gitlab-runner"
            # Drop ndots for quicker resolution
            [[runners.kubernetes.dns_config.options]]
              name = "ndots"
              value = "1"

    rbac:
      create: true
