---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 4.0.15
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    resources:
      requests:
        cpu: 1
        memory: 2G
      limits:
        cpu: 2
        memory: 4G
    replicas: 4
    persistence:
      enabled: true
      size: 10Gi
    buckets:
      - name: thanos
      - name: loki
  valuesFrom:
    - kind: Secret
      name: minio-values
