---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
    - kind: Secret
      name: minio-values
