---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm.yaml
secretGenerator:
  - name: minio-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
