apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-portal
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "pki.hm.edu"
        - "domain.api.hm.edu"
        - "pki.api.hm.edu"
        - "eab.api.hm.edu"
        - "acme.hm.edu"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: pki-cert
      hosts:
        - "pki.hm.edu"
        - "domain.api.hm.edu"
        - "pki.api.hm.edu"
        - "acme.hm.edu"
        - "eab.api.hm.edu"
    - port:
        number: 80
        name: http-stats
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "stats.it.hm.edu"
    - port:
        number: 443
        name: https-stats
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: stat-cert
      hosts:
        - "stats.it.hm.edu"
    - port:
        number: 80
        name: http-pwpusher
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "pwpusher.it.hm.edu"
    - port:
        number: 443
        name: https-pwpusher
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: pwpusher-cert
      hosts:
        - "pwpusher.it.hm.edu"
    - port:
        number: 80
        name: http-net
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "net.api.hm.edu"
    - port:
        number: 443
        name: https-net
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: tailscale-cert
      hosts:
        - "net.api.hm.edu"
    - port:
        number: 80
        name: http-workspaces
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "workspaces.it.hm.edu"
        - "*.workspaces.it.hm.edu"
    - port:
        number: 443
        name: https-workspaces
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: workspaces-cert
      hosts:
        - "workspaces.it.hm.edu"
        - "*.workspaces.it.hm.edu"