apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pki
  namespace: portal
spec:
  hosts:
    - pki.api.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: pki-rest-interface
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
  namespace: portal
spec:
  hosts:
    - pki.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: frontend
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: domain
  namespace: portal
spec:
  hosts:
    - domain.api.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: domain-rest-interface
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: eab
  namespace: portal
spec:
  hosts:
    - eab.api.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: eab-rest-interface
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: acme
  namespace: portal
spec:
  hosts:
    - acme.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: certificates
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: stats
  namespace: default
spec:
  hosts:
    - stats.it.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: grafana
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tailscale
  namespace: network
spec:
  hosts:
    - net.api.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: tailscale-webhook-service
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pwpush
  namespace: pwpush
spec:
  hosts:
    - pwpusher.it.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: pwpush-http
            port:
              number: 5100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab-workspaces
  namespace: gitlab-agent
spec:
  hosts:
    - workspaces.it.hm.edu
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: gitlab-workspaces-proxy-http
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab-workspaces-wildcard
  namespace: gitlab-agent
spec:
  hosts:
    - "*.workspaces.it.hm.edu"
  gateways:
    - istio-ingress/gateway-portal
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: gitlab-workspaces-proxy-http
            port:
              number: 80