apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-portal
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-acme
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - acme.hm.edu
    - port:
        number: 443
        name: https-acme
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
      hosts:
        - acme.hm.edu
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "pki.hm.edu"
        - "domain.api.hm.edu"
        - "pki.api.hm.edu"
        - "eab.api.hm.edu"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: portal-cert
      hosts:
        - "pki.hm.edu"
        - "domain.api.hm.edu"
        - "pki.api.hm.edu"
        - "eab.api.hm.edu"
    - port:
        number: 80
        name: http-meet
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "meet.hm.edu"
    - port:
        number: 443
        name: https-meet
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: meet-cert
      hosts:
        - "meet.hm.edu"
    - port:
        number: 80
        name: http-stats
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "stats.it.hm.edu"
    - port:
        number: 443
        name: https-stats
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: stat-cert
      hosts:
        - "stats.it.hm.edu"
    - port:
        number: 80
        name: http-net
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
        - "net.api.hm.edu"
    - port:
        number: 443
        name: https-net
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: net-cert
      hosts:
        - "net.api.hm.edu"