apiVersion: v1
kind: Secret
metadata:
    name: thanos-receive-basic-auth
    namespace: istio-ingress
type: Opaque
stringData:
    authorization: ENC[AES256_GCM,data:p5TaEiYj+Sl3il5lSi0aE+49tU0Ev0M2OruNZOaYuJQLYwmMTBoj9xf/672KrVoQ3XOreXcEg4tLf6E2HpnzYPet1acoXA==,iv:Ql3PeXHEeF8mOgoP+2ZCm9f6DHEfx8A6L1MjqfN3Fdo=,tag:FhHnmhaS3Aany/DONi5i2A==,type:str]
sops:
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3JHejhNNjByOGJDUlZH
            UUQ2TnBDVXVjVUFkY0ZJdnA1YktlcjV6WFZBCnFvcmluLzA5Z25HdFJ0eDNXYWJq
            MGFmdWdlZm5wMFA4NWpleHhQVXNuNTQKLS0tIG9xSmU4S21qelRKWjVUZm9yS3Bl
            RW1icHZYZW5RdloxOUE1WS82U1BuR28K0A8iSGYVcnmNUGVl3JkZ7bhzWfjhrRtR
            5gVkDSGGTXXU33aqfDPg+oP2Ogx5kzW78mTrw2UcEZK04zMO+LHn3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T17:52:09Z"
    mac: ENC[AES256_GCM,data:VQ9EIIilM5R9x7K9L/dl191OD2Mgqt7FQ65baY0PIw0HVRczSds80Mg5HGsXjApaRKzlmSfbENlljaxG5rUoMpfkLJ+c4V1NCLu5yyGvR0AGCj/O6tcPS/JORNSTrcDmvHsxeHLNKq/qscThWm/5gP16WR0yeUe0y4rC9NUcXZ8=,iv:HZRhmUKNBoio6CnaV5pyBxbghKSkYUeTM4dxVXneMVc=,tag:vJmiyoUmKzqKwoEAZaFF9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
