config:
    token: ENC[AES256_GCM,data:yrfboMmUl+igbNPuTRfLl5+O1/8xYXJQTY8TKiVw7qmntPsdafvPmnOJNoLtUp6qJG2/+9WaCm0Uzw==,iv:jQLHRfdS3M8SG7DTtOq3Q0sf0etXHkK33J4YlbvnIWw=,tag:YOCxb4iMiB9xTqvNL1HVAg==,type:str]
    kasAddress: ENC[AES256_GCM,data:g9Zu+VsUWNdgGTYB79v9zkJXxycP15gVFp2kRYIPFg4N3QEHSX3G,iv:zC82JVQ+eag+P+N/CzkqDwFLnn/AfIXhsUPbvL7rppU=,tag:3jgJrg4ZGFtMg0pqehvjNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n4ar7vyp3nmv844ep8ct4ea4d6uz7xflvug0pyz08ujek0ks2emsxzhn55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna0g0SGk3NFhKalN3L1VC
            WHZxd25SVGV0OE1kYW0xYnZCSy9TZ2dOUzBjCjYybWdTeEpmZjgwaWdIMTVRNStM
            cVpibmVNMnFKQTBIUTFIM1dPd2E5VEUKLS0tIFppb05vVjVmQ1FuN2dkTGxuTzdF
            aTdIblI3QnkzcVUvUERUaFArVWZRK0kKLV5fQ0t4lf2tae4O6x+dSXbwSlKqZtox
            hZMvvFIU9KvG/qzJnbau+d/k2vnH0AwUc+jHl7KUdgm7rz70Mo61IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-28T06:08:04Z"
    mac: ENC[AES256_GCM,data:SYTl5HjLN4wKEznk1HaaExqH2J+FMJZyRS7d7tkkSjkpu1Rk+dddyxYDOjKz2fBJnMVEJ5ca/gKD33tSumfaKI/4bhJXlUWf/MeDi6aJu+h+bfx6XvbDWtqeW4m+15aTQDe/h2mpQepE8zYt5rQrNSjispTtFyOz3cqWr3j6i1Q=,iv:C8ainkeGpZVGETz8Gyv/6gdtA7vGknL/C1qVMkEtVxU=,tag:CJR90Fj01cv8CmSL2PfIuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
