---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.44.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  values:
    image:
      repository: timberio/vector
      tag: 0.47.0-debian
    role: Stateless-Aggregator
    replicas: 3
    env:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.hostIP
      - name: SPLUNK_HEC_TOKEN
        valueFrom:
          secretKeyRef:
            name: vector
            key: splunk_hec_token
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: true
      sources:
        kubernetes_logs:
          type: vector
          address: 0.0.0.0:6010
          version: "2"
      transforms:
        kubernetes_logs_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |
            # Standardize 'app' index
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
            .host = "k8s.cc.private.hm.edu"
        kubernetes_logs_portal:
          type: filter
          inputs:
            - kubernetes_logs_remap
          condition: .kubernetes.pod_namespace == "portal"
        kubernetes_logs_portal_remap:
          type: remap
          drop_on_error: true
          reroute_dropped: true
          inputs:
            - kubernetes_logs_portal
          source: |
            # Try to extract JSON Message
            .message = parse_json!(.message)
        kubernetes_logs_other:
          type: filter
          inputs:
            - kubernetes_logs_remap
          condition: .kubernetes.pod_namespace != "portal"
      sinks:
        splunk:
          batch:
            max_bytes: 2049000
          encoding:
            codec: json
            only_fields:
              - container_name
              - custom_app_name
              - pod_name
              - kubernetes.pod_namespace
              - message
          endpoint: http://$NODE_IP:8088
          default_token: $SPLUNK_HEC_TOKEN
          inputs:
            - kubernetes_logs_portal_remap
            - kubernetes_logs_portal_remap.dropped
            - kubernetes_logs_other
          index: main
          type: splunk_hec_logs
          healthcheck:
            enabled: false
    containerPorts:
      - name: vector
        containerPort: 6010
        protocol: TCP
    service:
      enabled: true
      ports: 
        - name: vector
          port: 6010
          protocol: TCP
