---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.16.3
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
    crds: CreateReplace
  dependsOn:
    - name: loki
      namespace: monitoring
  values:
    image:
      repository: timberio/vector
      tag: 0.25.0-debian
    role: Stateless-Aggregator
    replicas: 3
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        journal_logs:
          type: vector
          address: 0.0.0.0:6000
          version: "2"
        kubernetes_logs:
          type: vector
          address: 0.0.0.0:6010
          version: "2"
      transforms:
        kubernetes_logs_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |
            # Standardize 'app' index
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"

        kubernetes_logs_portal:
          type: filter
          inputs:
            - kubernetes_logs_remap
          condition: .kubernetes.pod_namespace == "portal"
        kubernetes_logs_portal_remap:
          type: remap
          drop_on_error: true
          reroute_dropped: true
          inputs:
            - kubernetes_logs_portal
          source: |
            # Try to extract JSON Message
            .message = parse_json!(.message)

        kubernetes_logs_other:
          type: filter
          inputs:
            - kubernetes_logs_remap
          condition: .kubernetes.pod_namespace != "portal" && .container_name != "loki-canary"
        kubernetes_logs_canary:
          type: filter
          inputs:
            - kubernetes_logs_remap
          condition: .container_name == "loki-canary"
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes_canary:
          type: loki
          inputs:
            - kubernetes_logs_canary
          endpoint: http://loki-gateway:80
          encoding:
            codec: text
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            pod: >-
              {{`{{ pod_name }}`}}
            stream: >-
              {{`{{ stream }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs_portal_remap
            - kubernetes_logs_portal_remap.dropped
            - kubernetes_logs_other
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ custom_app_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
    service:
      enabled: true
      type: NodePort
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: vector-aggregator
            patch:
              - op: replace
                path: /spec/externalTrafficPolicy
                value: Local
