apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/hm-edu/portal-frontend:main-c59d6e8-1724704101 # {"$imagepolicy": "flux-system:frontend"}
          imagePullPolicy: Always
          name: app
          env:
            - name: EAB_HOST
              value: "https://eab.api.hm.edu"
            - name: PKI_HOST
              value: "https://pki.api.hm.edu"
            - name: DOMAIN_HOST
              value: "https://domain.api.hm.edu"
          envFrom:
            - secretRef:
                name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: portal
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
